apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
spec:
  containers:
  - name: mongodb
    imagePullPolicy: Always
    image: dockerswaha/mongodb:k8
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
    - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb

spec:
  selector:
    name: mongodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 27017
  