apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    mera: tera
spec:
  containers:
  - name: web
    imagePullPolicy: Always
    image: dockerswaha/web:k8
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "100m"
        memory: "128Mi"
    ports:
      containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: web-service

spec:
  type: LoadBalancer
  selector:
    mera: tera
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  